/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'ProcessTrigger': EventHandler<never, never>
    'CreateTrigger': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'CheckTriggers': CronHandler<{ topic: 'trigger-ready'; data: never }>
    'Signup User': ApiRouteHandler<Record<string, unknown>, unknown, never>
    ' User': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'Login User': ApiRouteHandler<Record<string, unknown>, unknown, never>
  }
    
}