/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'CreateTrigger': ApiRouteHandler<Record<string, unknown>, ApiResponse<201, { id: string; eventType: string; isActive: boolean; config: Record<string, unknown>; createdAt: string; updatedAt: string }> | ApiResponse<400, { error: string }> | ApiResponse<500, { error: string }>, never>
    'Signup User': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'Login User': ApiRouteHandler<Record<string, unknown>, unknown, never>
  }
    
}